version: '3'

volumes:
  db:

networks:
  dbbridge:
    driver: bridge

services:

  go-frontend:
    container_name: go-frontend
    build:
      context: ./frontend/
    depends_on:
      - redis-db
      - go-backend

  go-backend:
    container_name: go-backend
    build:
      context: ./backend/
    depends_on:
      - redis-db
    networks:
      - dbbridge

  redis-db:
    container_name: redis-db
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - "db:/data"
    networks:
      - dbbridge
