name: Build and Test
on:
  pull_request:
    branches: [ main ]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4   

      - name: Build frontend
        run: |
          cd frontend
          go build
      
      - name: Test fronend 
        run: |
          cd frontend
          go test

      - name: Build backend
        run: |
          cd backend
          go build
      
      - name: Test backend
        run: |
          cd backend
          go test
  

  CheckDocker: 
    runs-on: ubuntu-latest
    needs: [BuildAndTest]
    steps:
      - name: Clone down repository
        uses: actions/checkout@4
      
      - name: Build frontend docker image
        run: |
          cd frontend
          docker build 

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          dockerfile: Dockerfile
          push: false
          tags: frontend:latest

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          dockerfile: Dockerfile
          push: false
          tags: backend:latest
      
      - name: Deploy docker compose
        run: docker compose up

      - name: Test
        run: |
          sleep 20
          wget http://localhost:8080/
          test -f index.html

  BuildDocker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [CheckDocker]
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4  

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mrodense
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          dockerfile: Dockerfile
          push: true
          tags: ghcr.io/mrodense/frontend_simple_fortune:1.0-${{ github.sha }},ghcr.io/mrodense/frontend_simple_fortune:latest
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          dockerfile: Dockerfile
          push: true
          tags: ghcr.io/mrodense/frontend_simple_fortune:1.0-${{ github.sha }},ghcr.io/mrodense/backend_simple_fortune:latest

 
