name: main CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  REPO_NAME_BACKEND: ${{ secrets.REPO_NAME_BACKEND }}  
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down
        uses: actions/checkout@v2
      - name: Clone down
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    container: golang:latest
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: build backend
        run: cd backend && go build && cd ..
      - name: build frontend
        run: cd frontend && go build
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    steps: 
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: docker login
        run: | # log into docker hub account
          docker login -u ${{env.docker_username}} -p ${{env.docker_password}} 
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: docker build frontend 
        run: cd frontend && docker build . --file Dockerfile --tag $REPO_NAME:${{ steps.date.outputs.date }} && cd ..
      - name: Docker Push
        run: docker push $REPO_NAME:${{ steps.date.outputs.date }}
      - name: docker build backend # get the date of the build
        run: cd backend && docker build . --file Dockerfile --tag $REPO_NAME_BACKEND:${{ steps.date.outputs.date }}
      - name: Docker Push
        run: docker push $REPO_NAME_BACKEND:${{ steps.date.outputs.date }}
  Frontend-test:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    container: golang:latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Execute frontend test
        run: cd frontend && go test
  Automated-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
      - name: Download code
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Execute test
        run: chmod +x ci/test.sh && GIT_COMMIT="GA-$GITHUB_SHA" && ci/test.sh