name: main_release
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
  branch: 'main'
on:
  workflow_run:
    workflows: [Furtune_cookie_workflow]
    branches: 'main'
    types:
      - completed
jobs:
  Docker-image:
    name: Create Docker image and push it to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push backend Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ env.docker_username }}/simple-fortune-cookie_go-backend_${{ env.branch }}:latest-${{ env.GIT_COMMIT }}
      - name: Build and push frontend Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ env.docker_username }}/simple-fortune-cookie_go-frontend_${{ env.branch }}:latest-${{ env.GIT_COMMIT }}
  Run_app:
    name: Run application on GitHub runner service
      runs-on: ubuntu-latest
      steps:
        - name: Run startup script
          run: run ./app_start.sh ${{ env.branch }}