name: Worker
on:
  push:
    branches:
      - main
      - Build-Go
      - DockerLogin
  pull_request:
    branches:
      - main

env:
  docker_username: spedsbjerg
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  docker_repo: simple_fortune_cookie
  GIT_COMMIT: ${{ github.sha }}

jobs:
  GetGo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - run: go version
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: GoLang
          path: .

  BuildFrontEnd:
    runs-on: ubuntu-latest
    needs: GetGo
    steps:
      - uses: actions/checkout@v2
      - name: Build go.mod
        working-directory: frontend
        run: go build -v
      - uses: actions/upload-artifact@v3
        with:
          name: FrontBuild
          path: .

  TestFrontEnd:
    runs-on: ubuntu-latest
    needs: BuildFrontEnd
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/checkout@v2
      - name: Run Test
        working-directory: frontend
        run: go test -v .

  BuildBackEnd:
    runs-on: ubuntu-latest
    needs: GetGo
    steps:
      - uses: actions/checkout@v3
      - name: Build go.mod
        working-directory: backend
        run: go build -v
      - uses: actions/upload-artifact@v3
        with:
          name: BackBuild
          path: .

  TestBackEnd:
    runs-on: ubuntu-latest
    needs: BuildBackEnd
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/checkout@v2
      - name: Run Test
        working-directory: backend
        run: go test -v .

  PushToDuckerHub:
    runs-on: ubuntu-latest
    needs: [TestBackEnd, TestFrontEnd]
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 #https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
        with:
          username: ${{env.docker_username}}
          password: ${{env.docker_password}}
        
      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/backend | ghcr.io/frontend
           
      - name: Build and Push Frontend #starting with frontend, if it works, try both
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: spedsbjerg/simple_fortune_cookie:Frontend

      - name: Build and Push Backend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: spedsbjerg/simple_fortune_cookie:Backend
